// commandSQL01.js
import pkg from 'pg';
import dotenv from "dotenv";
dotenv.config();

const { Client } = pkg;

const client = new Client({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

async function createTables() {
  try {
    await client.connect();
    console.log("DB接続成功");

    // --- GENERATION ---
    await client.query(
    `
    CREATE TABLE GENERATION
    (
    GENERATIONID INTEGER PRIMARY KEY,
    SEDAI VARCHAR(5),
    GENERATION VARCHAR(15)
    );
    `);

    await client.query(
    `
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('01', '第01世代', 'Generation01');
    
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('02', '第02世代', 'Generation02');
    
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('03', '第03世代', 'Generation03');
    
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('04', '第04世代', 'Generation04');
    
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('05', '第05世代', 'Generation05');
    
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('06', '第06世代', 'Generation06');
    
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('07', '第07世代', 'Generation07');
    
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('08', '第08世代', 'Generation08');
    
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('09', '第09世代', 'Generation09');
    
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('10', '第10世代', 'Generation10');
    
    INSERT INTO GENERATION(GENERATIONID, SEDAI, GENERATION)
    VALUES('99', '第99世代', 'Generation99');
    `);

    // --- TYPE ---
    await client.query(
    `
    CREATE TABLE TYPE(
TYPEID INTEGER PRIMARY KEY,
TAIPU VARCHAR(10),
TYPE VARCHAR(10),
PATHTYPE VARCHAR(11)
);

    `);

    await client.query(
    `
    INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('01', 'ノーマル', 'NORMAL', 'type/01.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('02', 'ほのお', 'FIRE', 'type/02.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('03', 'みず', 'WATER', 'type/03.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('04', 'くさ', 'GRASS', 'type/04.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('05', 'でんき', 'ELECTRIC', 'type/05.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('06', 'こおり', 'ICE', 'type/06.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('07', 'かくとう', 'FIGHT', 'type/07.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('08', 'どく', 'POISON', 'type/08.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('09', 'じめん', 'GROUND', 'type/09.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('10', 'ひこう', 'FLYING', 'type/10.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('11', 'エスパー', 'PSYCHIC', 'type/11.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('12', 'むし', 'BUG', 'type/12.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('13', 'いわ', 'ROCK', 'type/13.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('14', 'ゴースト', 'GHOST', 'type/14.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('15', 'ドラゴン', 'DRAGON', 'type/15.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('16', 'あく', 'DARK', 'type/16.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('17', 'はがね', 'STEEL', 'type/17.png');

INSERT INTO TYPE(TYPEID, TAIPU, TYPE, PATHTYPE)
VALUES('18', 'フェアリー', 'FAIRY', 'type/18.png');
    `);

    // --- GENDER ---
    await client.query(
    `
    CREATE TABLE GENDER(
GENDERID INTEGER PRIMARY KEY,
GENDER VARCHAR(20)
);

    `);

    await client.query(
    `
    INSERT INTO GENDER(GENDERID, GENDER)
VALUES('01', '♂:50% ♀:50%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('02', '♂:75% ♀:25%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('03', '♂:25% ♀:75%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('04', '♂:87.5% ♀:12.5%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('05', '♂:12.5% ♀:87.5%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('06', '♂:100% ♀:0%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('07', '♂:0% ♀:100%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('08', '♂:? ♀:?');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('9', '♂:50% ♀:0%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('10', '♂:0% ♀:50%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('11', '♂:75% ♀:0%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('12', '♂:0% ♀:25%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('13', '♂:25% ♀:0%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('14', '♂:0% ♀:75%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('15', '♂:87.5% ♀:0%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('16', '♂:0% ♀:12.5%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('17', '♂:12.5% ♀:0%');

INSERT INTO GENDER(GENDERID, GENDER)
VALUES('18', '♂:0% ♀:87.5%');
    `);

    // --- EGG_GROUP ---
    await client.query(
    `
    CREATE TABLE EGG_GROUP(
EGG_GROUPID INTEGER PRIMARY KEY,
TAMAGO_GROUP VARCHAR(10),
EGG_GROUP VARCHAR(15)
);

    `);

    await client.query(
    `
    INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('01', '植物', 'Grass');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('02', '虫', 'Bug');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('03', '飛行', 'Flying');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('04', '人型', 'Human-Like');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('05', '怪獣', 'Monster');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('06', '妖精', 'Fairy');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('07', 'ドラゴン', 'Dragon');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('08', '鉱物', 'Mineral');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('09', '陸上', 'Field');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('10', '不定形', 'Amorphous');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('11', '水中1', 'Water1');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('12', '水中2', 'Water2');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('13', '水中3', 'Water3');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('14', 'メタモン', 'Ditto');

INSERT INTO EGG_GROUP(EGG_GROUPID, TAMAGO_GROUP, EGG_GROUP)
VALUES('15', '未発見', 'Undiscovered');
    `);

    // --- REGION ---
    await client.query(
    `
    CREATE TABLE REGION(
REGIONID INTEGER PRIMARY KEY,
CHIHO VARCHAR(15),
REGION VARCHAR(10)
);

    `);

    await client.query(
    `
    INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('01', 'カントー地方', 'Kanto');

INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('02', 'ジョウト地方', 'Johto');

INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('03', 'ホウエン地方', 'Hoenn');

INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('04', 'シンオウ地方', 'Sinnoh');

INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('05', 'イッシュ地方', 'Unova');

INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('06', 'カロス地方', 'Kalos');

INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('07', 'アローラ地方', 'Alola');

INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('08', 'ガラル地方', 'Galar');

INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('09', 'ヒスイ地方', 'Hisui');

INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('10', 'パルデア地方', 'Paldea');

INSERT INTO REGION(REGIONID, CHIHO, REGION)
VALUES('99', '地方', 'Unknown');
    `);

    // --- ABILITY ---
    await client.query(
    `
    CREATE TABLE ABILITY(
ABILITYID INTEGER PRIMARY KEY,
TOKUSEI VARCHAR(10),
ABILITY VARCHAR(20),
SETSUMEI TEXT(5),
EXPLANATION TEXT(5),
GENERATION INTEGER,
FOREIGN KEY (GENERATION) REFERENCES GENERATION(GENERATIONID)
);

    `);

    await client.query(
    `
    INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('001', 'しんりょく', 'Overgrow', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('002', 'もうか', 'Blaze', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('003', 'げきりゅう', 'Torrent', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('004', 'りんぷん', 'Shield Dust', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('005', 'だっぴ', 'Shed Skin', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('006', 'ふくがん', 'Compound Eyes', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('007', 'むしのしらせ', 'Swarm', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('008', 'するどいめ', 'Keen Eye', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('009', 'にげあし', 'Run Away', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('010', 'こんじょう', 'Guts', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('011', 'いかく', 'Intimidate', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('012', 'せいでんき', 'Static', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('013', 'すながくれ', 'Sand Veil', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('014', 'どくのトゲ', 'Poison Point', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('015', 'メロメロボディ', 'Cute Charm', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('016', 'もらいび', 'Flash Fire', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('017', 'せいしんりょく', 'Inner Focus', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('018', 'ようりょくそ', 'Chlorophyll', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('019', 'ほうし', 'Effect Spore', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('020', 'ありじごく', 'Arena Trap', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('021', 'ものひろい', 'Pickup', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('022', 'じゅうなん', 'Limber', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('023', 'しめりけ', 'Damp', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('024', 'ノーてんき', 'Cloud Nine', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('025', 'やるき', 'Vital Spirit', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('026', 'ちょすい', 'Water Absorb', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('027', 'シンクロ', 'Synchronize', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('028', 'クリアボディ', 'Clear Body', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('029', 'ヘドロえき', 'Liquid Ooze', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('030', 'いしあたま', 'Rock Head', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('031', 'がんじょう', 'Sturdy', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('032', 'どんかん', 'Oblivious', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('033', 'マイペース', 'Own Tempo', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('034', 'じりょく', 'Magnet Pull', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('035', 'はやおき', 'Early Bird', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('036', 'あついしぼう', 'Thick Fat', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('037', 'あくしゅう', 'Stench', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('038', 'ねんちゃく', 'Sticky Hold', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('039', 'シェルアーマー', 'Shell Armor', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('040', 'ふゆう', 'Levitate', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('041', 'ふみん', 'Insomnia', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('042', 'かいりきバサミ', 'Hyper Cutter', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('043', 'ぼうおん', 'Soundproof', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('044', 'ひらいしん', 'Lightning Rod', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('045', 'しぜんかいふく', 'Natural Cure', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('046', 'てんのめぐみ', 'Serene Grace', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('047', 'すいすい', 'Swift Swim', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('048', 'みずのベール', 'Water Veil', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('049', 'はっこう', 'Illuminate', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('050', 'ほのおのからだ', 'Flame Body', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('051', 'ちくでん', 'Volt Absorb', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('052', 'トレース', 'Trace', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('053', 'カブトアーマー', 'Battle Armor', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('054', 'プレッシャー', 'Pressure', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('055', 'めんえき', 'Immunity', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('056', 'はりきり', 'Hustle', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('057', 'ちからもち', 'Huge Power', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('058', 'かそく', 'Speed Boost', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('059', 'かげふみ', 'Shadow Tag', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('060', 'マグマのよろい', 'Magma Armor', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('061', 'きゅうばん', 'Suction Cups', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('062', 'すなおこし', 'Sand Stream', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('063', 'あめうけざら', 'Rain Dish', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('064', 'あめふらし', 'Drizzle', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('065', 'なまけ', 'Truant', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('066', 'ふしぎなまもり', 'Wonder Guard', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('067', 'ヨガパワー', 'Pure Power', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('068', 'プラス', 'Plus', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('069', 'マイナス', 'Minus', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('070', 'さめはだ', 'Rough Skin', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('071', 'しろいけむり', 'White Smoke', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('072', 'ひでり', 'Drought', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('073', 'ふしぎなうろこ', 'Marvel Scale', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('074', 'てんきや', 'Forecast', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('075', 'へんしょく', 'Color Change', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('076', 'エアロック', 'Air Lock', '03');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('077', 'ちどりあし', 'Tangled Feet', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('078', 'とうそうしん', 'Rivalry', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('079', 'マジックガード', 'Magic Guard', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('080', 'かんそうはだ', 'Dry Skin', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('081', 'いろめがね', 'Tinted Lens', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('082', 'テクニシャン', 'Technician', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('083', 'いかりのつぼ', 'Anger Point', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('084', 'ノーガード', 'No Guard', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('085', 'うるおいボディ', 'Hydration', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('086', 'スキルリンク', 'Skill Link', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('087', 'よちむ', 'Forewarn', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('088', 'すてみ', 'Reckless', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('089', 'てつのこぶし', 'Iron Fist', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('090', 'リーフガード', 'Leaf Guard', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('091', 'きもったま', 'Scrappy', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('092', 'スナイパー', 'Sniper', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('093', 'フィルター', 'Filter', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('094', 'かたやぶり', 'Mold Breaker', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('095', 'てきおうりょく', 'Adaptability', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('096', 'ダウンロード', 'Download', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('097', 'サンパワー', 'Solar Power', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('098', 'きょううん', 'Super Luck', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('099', 'くいしんぼう', 'Gluttony', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('100', 'はやあし', 'Quick Feet', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('101', 'ゆきがくれ', 'Snow Cloak', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('102', 'おみとおし', 'Frisk', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('103', 'ふくつのこころ', 'Steadfast', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('104', 'ポイズンヒール', 'Poison Heal', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('105', 'ノーマルスキン', 'Normalize', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('106', 'あとだし', 'Stall', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('107', 'たんじゅん', 'Simple', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('108', 'ハードロック', 'Solid Rock', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('109', 'きけんよち', 'Anticipation', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('110', 'アイスボディ', 'Ice Body', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('111', 'てんねん', 'Unaware', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('112', 'みつあつめ', 'Honey Gather', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('113', 'フラワーギフト', 'Flower Gift', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('114', 'よびみず', 'Storm Drain', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('115', 'ゆうばく', 'Aftermath', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('116', 'かるわざ', 'Unburden', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('117', 'ぶきよう', 'Klutz', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('118', 'たいねつ', 'Heatproof', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('119', 'ゆきふらし', 'Snow Warning', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('120', 'でんきエンジン', 'Motor Drive', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('121', 'スロースタート', 'Slow Start', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('122', 'ナイトメア', 'Bad Dreams', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('123', 'マルチタイプ', 'Multitype', '04');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('124', 'はとむね', 'Big Pecks', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('125', 'きんちょうかん', 'Unnerve', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('126', 'すなかき', 'Sand Rush', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('127', 'ちからずく', 'Sheer Force', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('128', 'フレンドガード', 'Friend Guard', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('129', 'すりぬけ', 'Infiltrator', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('130', 'ミラクルスキン', 'Wonder Skin', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('131', 'すなのちから', 'Sand Force', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('132', 'まけんき', 'Defiant', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('133', 'せいぎのこころ', 'Justified', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('134', 'さいせいりょく', 'Regenerator', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('135', 'アナライズ', 'Analytic', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('136', 'どくしゅ', 'Poison Touch', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('137', 'ぼうじん', 'Overcoat', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('138', 'のろわれボディ', 'Cursed Body', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('139', 'くだけるよろい', 'Weak Armor', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('140', 'しゅうかく', 'Harvest', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('141', 'いやしのこころ', 'Healer', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('142', 'じしんかじょう', 'Moxie', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('143', 'びびり', 'Rattled', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('144', 'かわりもの', 'Imposter', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('145', 'マルチスケイル', 'Multiscale', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('146', 'マジックミラー', 'Magic Bounce', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('147', 'そうしょく', 'Sap Sipper', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('148', 'いたずらごころ', 'Prankster', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('149', 'テレパシー', 'Telepathy', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('150', 'あまのじゃく', 'Contrary', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('151', 'わるいてぐせ', 'Pickpocket', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('152', 'ムラっけ', 'Moody', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('153', 'ライトメタル', 'Light Metal', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('154', 'ヘヴィメタル', 'Heavy Metal', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('155', 'どくぼうそう', 'Toxic Boost', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('156', 'ねつぼうそう', 'Flare Boost', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('157', 'ダルマモード', 'Zen Mode', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('158', 'ミイラ', 'Mummy', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('159', 'よわき', 'Defeatist', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('160', 'イリュージョン', 'Illusion', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('161', 'てつのトゲ', 'Iron Barbs', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('162', 'ターボブレイズ', 'Turboblaze', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('163', 'テラボルテージ', 'Teravolt', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('164', 'しょうりのほし', 'Victory Star', '05');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('165', 'かちき', 'Competitive', '06');



INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('166', 'かたいツメ', 'Tough Claws', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('167', 'メガランチャー', 'Mega Launcher', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('168', 'おやこあい', 'Parental Bond', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('169', 'スカイスキン', 'Aerilate', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('170', 'フェアリースキン', 'Pixilate', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('171', 'フリーズスキン', 'Refrigerate', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('172', 'がんじょうあご', 'Strong Jaw', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('173', 'ぼうだん', 'Bulletproof', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('174', 'マジシャン', 'Magician', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('175', 'へんげんじざい', 'Protean', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('176', 'ほおぶくろ', 'Cheek Pouch', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('177', 'はやてのつばさ', 'Gale Wings', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('178', 'フラワーベール', 'Flower Veil', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('179', 'きょうせい', 'Symbiosis', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('180', 'くさのけがわ', 'Grass Pelt', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('181', 'ファーコート', 'Fur Coat', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('182', 'バトルスイッチ', 'Stance Change', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('183', 'アロマベール', 'Aroma Veil', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('184', 'スイートベール', 'Sweet Veil', '06');


INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('185', 'ぬめぬめ', 'Gooey', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('186', 'フェアリーオーラ', 'Fairy Aura', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('187', 'ダークオーラ', 'Dark Aura', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('188', 'オーラブレイク', 'Aura Break', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('189', 'はじまりのうみ', 'Primordial Sea', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('190', 'おわりのだいち', 'Desolate Land', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('191', 'デルタストリーム', 'Delta Stream', '06');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('192', 'サーフテール', 'Surge Surfer', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('193', 'ゆきかき', 'Slush Rush', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('194', 'カーリーヘア', 'Tangling Hair', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('195', 'エレキスキン', 'Galvanize', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('196', 'かがくのちから', 'Power of Alchemy', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('197', 'えんかく', 'Long Reach', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('198', 'うるおいボイス', 'Liquid Voice', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('199', 'はりこみ', 'Stakeout', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('200', 'バッテリー', 'Battery', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('201', 'おどりこ', 'Dancer', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('202', 'ぎょぐん', 'Schooling', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('203', 'ひとでなし', 'Merciless', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('204', 'じきゅうりょく', 'Stamina', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('205', 'すいほう', 'Water Bubble', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('206', 'ふしょく', 'Corrosion', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('207', 'もふもふ', 'Fluffy', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('208', 'じょおうのいげん', 'Queenly Majesty', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('209', 'ヒーリングシフト', 'Triage', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('210', 'レシーバー', 'Receiver', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('211', 'にげごし', 'Wimp Out', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('212', 'ききかいひ', 'Emergency Exit', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('213', 'みずがため', 'Water Compaction', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('214', 'とびだすなかみ', 'Innards Out', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('215', ' ARシステム', 'RKS System', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('216', 'リミットシールド', 'Shields Down', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('217', 'ぜったいねむり', 'Comatose', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('218', 'ばけのかわ', 'Disguise', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('219', 'ビビッドボディ', 'Dazzling', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('220', 'ぎゃくじょう', 'Berserk', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('221', 'はがねつかい', 'Steelworker', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('222', 'エレキメイカー', 'Electric Surge', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('223', 'サイコメイカー', 'Psychic Surge', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('224', 'グラスメイカー', 'Grass Surge', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('225', 'ミストメイカー', 'Misty Surge', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('226', 'メタルプロテクト', 'Full Metal Body', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('227', 'ファントムガード', 'Shadow Shield', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('228', 'ビーストブースト', 'Beast Boost', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('229', 'プリズムアーマー', 'Prism Armor', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('230', 'ブレインフォース', 'Neuroforce', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('231', 'ソウルハート', 'Soul-Heart', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('232', 'きずなへんげ', 'Battle Bond', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('233', 'スワームチェンジ', 'Power Construct', '07');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('234', 'パステルベール', 'Pastel Veil', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('235', 'クイックドロウ', 'Quick Draw', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('236', 'かがくへんかガス', 'Neutralizing Gas', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('237', 'バリアフリー', 'Screen Cleaner', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('238', 'きみょうなくすり', 'Curious Medicine', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('239', 'ごりむちゅう', 'Gorilla Tactics', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('240', 'さまようたましい', 'Wandering Spirit', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('241', 'ぎたい', 'Mimicry', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('242', 'リベロ', 'Libero', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('243', 'ミラーアーマー', 'Mirror Armor', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('244', 'わたげ', 'Cotton Down', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('245', 'たまひろい', 'Ball Fetch', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('246', 'じょうききかん', 'Steam Engine', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('247', 'じゅくせい', 'Ripen', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('248', 'すなはき', 'Sand Spit', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('249', 'うのミサイル', 'Gulp Missile', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('250', 'スクリューおびれ', 'Propeller Tail', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('251', 'パンクロック', 'Punk Rock', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('252', 'はがねのせいしん', 'Steely Spirit', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('253', 'ほろびのボディ', 'Perish Body', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('254', 'こおりのりんぷん', 'Ice Scales', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('255', 'パワースポット', 'Power Spot', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('256', 'アイスフェイス', 'Ice Face', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('257', 'はらぺこスイッチ', 'Hunger Switch', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('258', 'すじがねいり', 'Stalwart', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('259', 'ふとうのけん', 'Intrepid Sword', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('260', 'ふくつのたて', 'Dauntless Shield', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('261', 'ふかしのこぶし', 'Unseen Fist', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('262', 'トランジスタ', 'Transistor', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('263', 'りゅうのあぎと', 'Dragon’s Maw', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('264', 'しろのいななき', 'Chilling Neigh', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('265', 'くろのいななき', 'Grim Neigh', '08');

INSERT INTO ABILITY (ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('266', 'じんばいったい', 'As One', '08');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('267', 'はんすう', 'Cud Chew', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('268', 'きれあじ', 'Sharpness', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('269', 'しんがん', 'Mind’s Eye', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('270', 'とれないにおい', 'Lingering Aroma', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('271', 'こんがりボディ', 'Well-Baked Body', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('272', 'こぼれダネ', 'Seed Sower', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('273', 'きよめのしお', 'Purifying Salt', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('274', 'でんきにかえる', 'Electromorphosis', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('275', 'ふうりょくでんき', 'Wind Power', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('276', 'ばんけん', 'Guard Dog', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('277', 'かぜのり', 'Wind Rider', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('278', 'きんしのちから', 'Mycelium Might', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('279', 'いかりのこうら', 'Anger Shell', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('280', 'びんじょう', 'Opportunist', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('281', 'いわはこび', 'Rocky Payload', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('282', 'マイティチェンジ', 'Zero to Hero', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('283', 'どしょく', 'Earth Eater', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('284', 'どくげしょう', 'Toxic Debris', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('285', 'きょうえん', 'Costar', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('286', 'しれいとう', 'Commander', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('287', 'テイルアーマー', 'Armor Tail', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('288', 'そうだいしょう', 'Supreme Overlord', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('289', 'こだいかっせい', 'Protosynthesis', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('290', 'クォークチャージ', 'Quark Drive', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('291', 'ねつこうかん', 'Thermal Exchange', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('292', 'おうごんのからだ', 'Good as Gold', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('293', 'わざわいのおふだ', 'Tablets of Ruin', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('294', 'わざわいのつるぎ', 'Sword of Ruin', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('295', 'わざわいのうつわ', 'Vessel of Ruin', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('296', 'わざわいのたま', 'Beads of Ruin', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('297', 'ひひいろのこどう', 'Orichalcum Pulse', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('298', 'ハドロンエンジン', 'Hadron Engine', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('299', 'かんろなミツ', 'Supersweet Syrup', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('300', 'おもてなし', 'Hospitality', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('301', 'どくのくさり', 'Toxic Chain', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('302', 'テラスチェンジ', 'Tera Shift', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('303', 'テラスシェル', 'Tera Shell', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('304', 'ゼロフォーミング', 'Teraform Zero', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('305', 'どくくぐつ', 'Poison Puppeteer', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('306', 'おもかげやどし', 'Embody Aspect', '09');

INSERT INTO ABILITY(ABILITYID, TOKUSEI, ABILITY, GENERATION)
VALUES('999', '未確認', 'Unknown', '99');
    `);

    // --- pokedex1 ---
    await client.query(
    `
    CREATE TABLE pokedex1(
POKEID INTEGER PRIMARY KEY,
NO VARCHAR(5),
NAMAE VARCHAR(20),
NAME VARCHAR(20),
SUGATA VARCHAR(20),
FORM VARCHAR(40),
BUNRUI VARCHAR(20),
CLASSIFICATION VARCHAR(25),

TYPE1 INTEGER,
TYPE2 INTEGER,
ABILITY1 INTEGER,
ABILITY2 INTEGER,
HIDDEN_ABILITY INTEGER,
GENDER INTEGER,
EGG_GROUP1 INTEGER,
EGG_GROUP2 INTEGER,
REGION INTEGER,
GENERATION INTEGER,
AUTONUM INTEGER,

FOREIGN KEY (TYPE1) REFERENCES TYPE(TYPEID),
FOREIGN KEY (TYPE2) REFERENCES TYPE(TYPEID),
FOREIGN KEY (ABILITY1) REFERENCES ABILITY(ABILITYID),
FOREIGN KEY (ABILITY2) REFERENCES ABILITY(ABILITYID),
FOREIGN KEY (HIDDEN_ABILITY) REFERENCES ABILITY(ABILITYID),
FOREIGN KEY (GENDER) REFERENCES GENDER(GENDERID),
FOREIGN KEY (EGG_GROUP1) REFERENCES EGG_GROUP(EGG_GROUPID),
FOREIGN KEY (EGG_GROUP2) REFERENCES EGG_GROUP(EGG_GROUPID),
FOREIGN KEY (REGION) REFERENCES REGION(REGIONID),
FOREIGN KEY (GENERATION) REFERENCES GENERATION(GENERATIONID)
);
    `);

    // --- pokedex2 ---
    await client.query(
    `
    CREATE TABLE pokedex2(
POKEID INTEGER PRIMARY KEY,
NO VARCHAR(5),
NAME VARCHAR(20),
FORM VARCHAR(20),

HP INTEGER,
ATTACK INTEGER,
DEFENSE INTEGER,
SP_ATK INTEGER,
SP_DEF INTEGER,
SPEED INTEGER,
SUM INTEGER
);

    `);

    // --- pokedex3 ---
    await client.query(
    `
    CREATE TABLE pokedex3 (
POKEID INTEGER PRIMARY KEY,
NO VARCHAR(5),
NAME VARCHAR(20),
FORM VARCHAR(20),

PATH_NORMAL_FRONT VARCHAR(50),
PATH_NORMAL_BACK VARCHAR(50),
PATH_SHINY_FRONT VARCHAR(50),
PATH_SHINY_BACK VARCHAR(50)
);
    `);

    // --- pokedex4 ---
    await client.query(
    `
    CREATE TABLE pokedex4 (
POKEID INTEGER PRIMARY KEY,
NO VARCHAR(5),
NAME VARCHAR(20),
FORM VARCHAR(20),

PATH_TYPECHART_BRIGHT VARCHAR(50),
PATH_TYPECHART_DARK VARCHAR(50)
);
    `);
    
    console.log("すべてのテーブル作成 & 初期データ挿入が完了しました！");
  } catch (err) {
    console.error("SQL実行エラー:", err);
  } finally {
    await client.end();
    console.log("DB接続終了");
  }
}

createTables();
